logo = '''
                         ___________
                         \         /
                          )_______(
                          |"""""""|_.-._,.---------.,_.-._
                          |       | | |               | | ''-.
                          |       |_| |_             _| |_..-'
                          |_______| '-' `'---------'` '-'
                          )"""""""(
                         /_________\\
                       .-------------.
                      /_______________\\
'''

auction_items = [
    "Antique Pocket Watch",
    "Vintage Persian Rug",
    "Rare Stamp Collection",
    "Signed Picasso Print",
    "Diamond Tennis Bracelet",
    "Classic Car - 1965 Mustang",
    "Vintage Vinyl Record Set",
    "Limited Edition Sneaker Collection",
    "Historical Autographed Document",
    "Original Watercolor Painting",
    "First Edition Book Collection",
    "Ancient Sculpture Replica",
    "Gold-Plated Tea Set",
    "Custom-Made Guitar",
    "Luxury Cruise Vacation Package",
    "Designer Handbag Collection",
    "Antique Telescope",
    "Private Wine Tasting Experience",
    "Rare Coin Collection",
    "Handcrafted Wooden Furniture Set",
    "Hot Air Balloon Ride",
    "Exclusive VIP Concert Tickets",
    "Private Chef for a Day",
    "Personalized Star Naming Certificate",
    "Custom Tailored Suit",
    "Exotic Animal Safari Adventure",
    "Handwritten Song Lyrics by a Famous Artist",
    "Exclusive Artisanal Chocolate Box",
    "Vintage Movie Poster Collection",
    "Original Concept Artwork from a Film",
    "Luxury Watch Collection",
    "Weekend Getaway at a Spa Resort",
    "Customized Home Theater System",
    "Private Helicopter Tour",
    "Sports Memorabilia Collection",
    "Luxury Yacht Charter",
    "Vintage Champagne Set",
    "Adventure Trip to the Amazon Rainforest",
    "Rare Gemstone Collection",
    "Custom Portrait Painting",
    "Handwoven Silk Tapestry",
    "Exclusive Wine Cellar Membership",
    "Historical Manuscript",
    "Sculpted Marble Fountain",
    "Limited Edition Board Game Set",
    "Private Golf Lesson with a Pro",
    "Vintage Motorcycle",
    "Exquisite Crystal Chandelier",
    "Themed Dinner Experience with a Chef",
    "Original Hand-Drawn Comic Book Art",
    "Gold Bullion Bar",
    "Designer Sunglasses Collection",
    "Helium Balloon Ride to the Edge of Space",
    "Classic Fountain Pen Collection",
    "Hand-Painted Ceramic Vases",
    "Custom-Made Surfboard",
    "Private Jet Getaway Weekend",
    "Rare Caviar Tasting Set",
    "Handcrafted Jewelry Collection",
    "Vintage Typewriter",
    "Personalized Star Map",
    "Diamond-Encrusted Cufflinks",
    "Exclusive Fashion Show Tickets",
    "Authentic Samurai Sword",
    "Private Dance Lessons with a Celebrity Choreographer",
    "Original Broadway Show Costume",
    "Exotic Orchid Collection",
    "Private Yoga Retreat",
    "Limited Edition Smartphone",
    "Exclusive Fashion Designer Workshop",
    "Classic Arcade Game Collection",
    "Luxury Artisanal Soap Set",
    "Custom-Made Racing Bicycle",
    "Private Hot Air Balloon Festival Viewing",
    "Rare Butterfly Taxidermy Collection",
    "Hand-Crafted Leather Journal",
    "Private Cooking Class with a Renowned Chef",
    "Vintage Fountain Pen Set",
    "Artificial Intelligence Portrait",
    "Exclusive Perfume Collection",
    "Authentic Native American Artifacts",
    "Weekend Retreat at a Medieval Castle",
    "Historical Pocket Watch Collection",
    "Custom-Made Leather Shoes",
    "Vintage Record Player",
    "Private Glassblowing Workshop",
    "Original Science Fiction Manuscript",
    "Limited Edition Craft Beer Collection",
    "Luxury Picnic Basket Set",
    "Exclusive Wildlife Photography Safari",
    "Private Concert in Your Backyard",
    "Antique Map Collection",
    "Custom-Made Racing Car Experience",
    "Vintage Train Set",
    "Hand-Painted Silk Scarf Collection",
    "Private Sailing Lesson with a Captain",
    "Rare Bonsai Tree Collection",
    "Exclusive Virtual Reality Gaming System",
    "Authentic World War II Memorabilia",
    "Private Horseback Riding Adventure",
    "Original Manuscript by a Nobel Laureate",
    "Handmade Chess Set",
    "Exclusive Telescope for Stargazing",
    "Luxury Beachfront Villa Rental",
    "Custom-Made Wedding Dress",
    "Vintage Wine Barrel Furniture Set",
]